[package]
name = "adventofcode_lmh01_lib"
version = "2.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = {version = "3.2.0", features = ["fancy"] }
